FirstDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #
    path('admin/', admin.site.urls),
    # ^book以book开头的网址，如何处理呢? 查询bookAPP.urls里面的路由设置
    path('book/', include('bookApp.urls'))
]

bookApp/urls.py
from django.contrib import admin
from django.urls import path, re_path
# .代表当前目录， 从当前目录导入views模块
from . import  views

# 路由处理: 当客户端访问网址的时候， 交给哪一个函数去处理客户端的请求并返回响应。
urlpatterns = [
    # name='index'是给views.index起的一个别名，便于后续的处理
    path('', views.index, name='index'),
    # 设计访问书籍详情信息的url地址, 如下:
    # http://127.0.0.1:8000/book/1/
    # http://127.0.0.1:8000/book/2/
    # http://127.0.0.1:8000/book/3/
    # Django2中path的路由可以使用正则匹配, Django3中不能, 需要使用re_path
    # 正则的规则: [0-9]代表单个数字, \d也代表单个数字, +代表前面的字符出现1次或者多次.
    # 正则中的()代表分组,这里将()里面匹配到的内容传递给detail函数.
    # re_path('([0-9]+)/$', views.detail, name='detail'),
    # 注意: int代表整型, id代表将传入的整形数值存储到id变量中,传给视图函数
    path('<int:id>/', views.detail, name='detail')

]

bookApp/models.py
from django.db import models


# Create your models here.
# 一个Book类对应一个数据库表
# 一个类属性对应一个数据库表的列属性
class Book(models.Model):
    # # 默认情况下，会自动添加id这一列作为主键。
    # title是字符串类型的， 并且最大的长度为20;
    title = models.CharField(max_length=20)
    pub_date = models.DateField()
    # 字符串的友好展示, 在交互式环境测试的时候生效
    def __repr__(self):
        return '<Book: %s>' % (self.title)
    # 字符串友好展示，在后台管理的时候生效
    def __str__(self):
        return self.title

    # 自定义对应的表名，默认表名：bookApp_book
    class Meta:
        db_table = "books"
        # 后台管理显示（单数）
        verbose_name = "图书管理"
        # 后台管理显示（复数）
        verbose_name_plural = "图书管理"


class Hero(models.Model):
    # 默认情况下，会自动添加id这一列作为主键。
    name = models.CharField(max_length=20)
    gender = models.BooleanField(default=True)
    content = models.CharField(max_length=200)
    # 一对多关系， 外键写在多的一端(Book:Hero=1:n)
    # models.CASCADE叫级联删除，当书籍被删除后，关联的任务也会被删除
    book = models.ForeignKey('Book', on_delete=models.CASCADE)

    def __repr__(self):
        return "<Hero %s>" % (self.name)

    def __str__(self):
        return self.name

    def sex(self):
        if self.gender:
            return  "男"
        else:
            return  '女'

    # 自定义对应的表名，默认表名：bookApp_book
    class Meta:
        db_table = "heros"
        # 后台管理显示（单数）
        verbose_name = "人物管理"
        # 后台管理显示（复数）
        verbose_name_plural = "人物管理"

bookApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book


# Create your views here.
# 编写第一个视图函数, http协议(基于请求-响应的一个协议, request-response)
def index(request):
    """书籍管理的首页, 显示所有的书籍信息"""
    # 查询数据库中所有的书籍信息
    books = Book.objects.all()
    # render租用/获取index.html的前端界面, 每次访问前端显示的信息不同, 取决于book书籍的信息
    return render(request, 'bookApp/index.html', {'books': books})
    # return HttpResponse("图书管理系统")


def detail(request, id):
    """访问书籍详情信息的函数"""
    # 从Book书籍表中寻找id=1/2/3(url中需要查询的书籍id)的详细信息
    book = Book.objects.get(id=id)
    # info = """
    # 书籍id: %s
    # 书籍名称: %s
    # 书籍发布日期:%s
    # """ %(book.id, book.title, book.pub_date)
    # # 视图函数,传入一个http请求,返回一个http响应
    # return HttpResponse(info)

    return render(request, 'bookApp/detail.html', {'book': book})

templates/bookApp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书详情页</title>
</head>
<body>
<h1>图书名称: {{ book.title }}</h1>
<h3>图书编号: {{ book.id }}</h3>
<h3>图书发布日期: {{ book.pub_date }}</h3>
<h3>图书人物信息: </h3>
{% if book.hero_set.all %}
    <ul>
    {% for hero in book.hero_set.all %}
        <li>{{ hero.name }}-{{ hero.content }}</li>
    {% endfor %}
    </ul>
{% else %}
    <h6 style="color: mediumvioletred">书籍{{ book.title }}没有人物信息</h6>
{% endif %}
</body>
</html>

templates/bookApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书管理系统</title>
</head>
<body>
<ul>
    {% for book in books %}
        <li><a href="/book/{{ book.id }}/">{{ book.id }}-{{ book.title }}</a></li>
    {% endfor %}
</ul>
</body>
</html>